services:
  backend:
    image: tiliadis/currencycalculator-backend:latest
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npm run seed && npm start"

  frontend:
    image: tiliadis/currencycalculator-frontend:latest
    container_name: frontend
    ports:
      - "5173:5173"
    env_file:
      - .env
    depends_on:
      - backend

  db:
    image: postgres:14
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data # mount to save data persistently
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  db_data:
